sudo: false
language: node_js
group: travis_latest
node_js: 9
os: linux

cache:
  directories:
    - node_modules
before_cache: rm -rf ./node_modules/.cache

std_job: &std_job
  stage: &std_stage_name Test & Lint
  addons: &browsers
    chrome: stable
    firefox: latest
  before_install: node ./ci/TravisMgr.js set-version
  after_success: cat ./coverage/lcov.info | coveralls

osx_job: &osx_job
  <<: *std_job
  os: osx
  osx_image: xcode9.2
  sudo: required
  addons:
    apt:
      packages:
        - xvfb
  before_script:
    - "export DISPLAY=:99.0"
    - sudo Xvfb :99 -ac -screen 0 1024x768x8 &
    - sleep 3
  script: npm test -- --browsers Safari

stages:
  - *std_stage_name
  - name: GitHub Deploy
    if: tag IS present
  - name: NPM Deploy
    if: tag IS present

before_install: &wake_server curl https://gh-contrib-parser-public.herokuapp.com/ping &

lint_job: &lint_job
  stage: *std_stage_name
  script: npm run tslint

npm_deploy: &npm_deploy
  stage: NPM Deploy
  script: gulp build
  before_install: node ./ci/TravisMgr.js set-version
  deploy:
    - provider: npm
      on:
        tags: true
      skip_cleanup: true
      email: a.molcanovas@gmail.com
      api_key:
        secure: y9mWjsAs+VionutmmZcj8kN1TFBmyHSA+U3+kgrKPsbF0D/JFb2rOuSUNILOp7I7ZsvAbRLvn8kg+1Ek03/2DZ6WD13CtzKB9sDSyQKh9Q9nPQu6YmYJvPo+/Wej45fUSyIOEHZygaejJh7SWNGOkX61ClTf9zJJPKndsRvVYI5lTp+smD/UaWmsnDpYlk1NOo1TE1K3WqRBMMYYi+I+v89GhYGA12voMV973ynIAG5leUjrkFxvAkXK5mAw9t0SIBJD3Wlsifkqy/KMpCDnb6m9TP4fwf634zGDW5BcG8uvmaLl9YtVL3OvNQa5DNbW6sfs11XejZKDt2p/OqaFVOEfX5dFpkbKTKruo6vWuiK0A/cEBI+yWdEK1mXU+PJS0WgUOzwfOAPvaDvzgs1AyqC7WYtS9HMohFkIGypO4gnE7OMJ2Ec4Yt8015CZC94K+h1E/andkKMBkNlsf3BNcn8IhXHbN1tn4yOATIRliHmG/qnLOY5KZmOClXNmUY4WmqUjaahcrnz0ai8hFpB4ExHkLStkqgcucm9Sgw6N1DbmjNilRIiLl4YIFq7JmU8bM9UzqqrU0n4/9RfxS4hjm6l/8puydaI/NND4m/9emAJXwN4Y5xmVUjgXuMGa51IAQyguhjpOD7/Xfg/GixlkIfCOk4p0kTFbT1irK3CGn84=

jobs:
  include:
    - <<: *lint_job
      env:
        - LINT=1
        - CI_NG_VERSION=5
    - <<: *osx_job
      env:
        - CI_NG_VERSION=5
    - <<: *osx_job
      env:
        - CI_NG_VERSION=4
    - <<: *std_job
      env:
        - CI_NG_VERSION=5
      script:
        - gulp build
        - tsc -p tsconfig.json
        - npm test
        - if [ $TRAVIS_TAG ]; then gulp site; else build:demo:aot; fi;
    - <<: *std_job
      env:
        - CI_NG_VERSION=4
      script:
        - gulp build
        - tsc -p tsconfig.json
        - npm test
    - stage: GitHub Deploy
      before_install: node ./ci/TravisMgr.js set-version
      env:
        - CI_NG_VERSION=5
      script: gulp site
      deploy:
        - provider: pages
          skip_cleanup: true
          on:
            tags: true
          local_dir: ./.demo
          target_branch: gh-pages
          github_token: &gh_token_noenv
            secure: "ilvBBuJbYKefovNLs/qqN27foTfc/+8N0ajHBHIWrToFvzoR9vMXFHlFDoDqWAGNA7XE6hkRfcnh0mwScbiZq5f/rWhWPskBk9fkXsNlFGCY0jpHEl01JmUb0SjCaiB9F6S0rqVyUXGFjd5RIizML72jebsDYYVpkpdY3iHzj1n6LVw5MQ4xgRzrSSHBKH++POQ2Gp/Pj6N4ayMQmHg3uWsKNJ1+37rD9Mg2G0kc6iAxwjRWuSDd2PGIMAmeJqGfECx9SVfV7HuLbdQjQjLkBIEodFbrIkgk+kY2LEc0o6Y8vAAFBYuSK2AujNYK/LL2B8bx/eU1To4DEgv17gXdMhogYFXd6FqTtwBPKAKda+ik1KIB7kkg+PjoGJ/kKa7H0YBgWpjmwqL4K5EmIDZIQLH+knn/thReZr4ksYpkFwRAtQbCgstdVFAMlqlGp9v6xqfU+HxyS2oBctPyEuRO2N1izAdrkPMxaOjOsj2YVpfe4oHooOrwHp3Hp9dthKSpUaBia1cPNoNgFJU+oI6eb4QfNcYEu9gAb2bLfK+kR9UNRpaGe47W+oMnQP+w2zIztPx2aReZPO6Yc12C3+jxgKs9vWOenWRYHWaWgFeNhuHY9wVgVN56ZZAbwEU8CP5/ou8UC9XRO59mSKONSaNHd6GPukveSFL2U4F3/jYYGfA="
        - provider: releases
          skip_cleanup: true
          on:
            tags: true
          api_key: *gh_token_noenv
          file: documentation.tar.gz
    - <<: *npm_deploy
      env:
        - CI_NG_VERSION=5
    - <<: *npm_deploy
      env:
        - CI_NG_VERSION=4
